name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff mypy pandas || true
      - name: Auto-fix linting and formatting errors
        run: |
          if command -v ruff >/dev/null 2>&1; then
            ruff check . --fix
          else
            echo "ruff not installed; auto-fix step skipped"
          fi
      - name: Run tests
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest -q
          else
            echo "pytest not installed; step skipped"
          fi
      - name: Lint
        run: |
          if command -v ruff >/dev/null 2>&1; then
            ruff check .
          else
            echo "ruff not installed; step skipped"
          fi
      - name: Type check
        run: |
          if command -v mypy >/dev/null 2>&1; then
            mypy src
          else
            echo "mypy not installed; step skipped"
          fi
